targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - document_ignores
            - implicit_dynamic_parameter
            - cast_nullable_to_non_nullable
            - require_trailing_commas
            - lines_longer_than_80_chars
            - specify_nonobvious_property_types
      json_serializable:
        options:
          create_to_json: false
          checked: true
